### ISSUE TITLE
My bloons TD battles exe file is wrongly named and the software cannot read it

### ISSUE THREAD

**Issue by httphypixelnet-bob** [TDToolbox/BTDToolbox#230]

**Comment by DisabledMallis** [comment]
Could you elaborate on the steps that caused this issue to happen?

**Comment by httphypixelnet-bob** [comment]
So like I cannot make a mod because my bloons td battles exe file is
Bloons-battlesWinRT-windows.exe. And the program only uses
Bloons-battles.exe

**Comment by DisabledMallis** [comment]
You must use the Steam version, the windows store/UWP version **will not** (and likely never will) work with btd toolbox

**Comment by httphypixelnet-bob** [comment]
Oh ok
