### ISSUE TITLE
macOS Compatibility?

### ISSUE THREAD

**Issue by SupaGamer2017** [TDToolbox/BTDToolbox#237]
Hello,

I'm interested in dipping my toes into the water for BTDB modding. However, I noticed that there is no official release for macOS, only Windows. Would it be possible to compile the program to run it on Mac from the source code, or would there be compatibility issues?

Thanks!

**Comment by DisabledMallis** [comment]
This program is no longer being worked on by us, and as such no official MacOS compatibility is planned. You may be able to port it, or maybe even get it working with something like wine, but I'm not sure what that would look like. Also, this program uses WinForms, which is a windows specific C# library that comes with .NET Framework, so you'd have to find a way to make that work on MacOS.
